### ISSUE TITLE
count of affected hosts in summary does not match with real count of hosts 

### ISSUE THREAD

**Issue by 4thomasmueller** [TheGroundZero/openvasreporting_server#4]
Hello,

we did scan 2 (two) hosts and we've got a total amount of 18 affected hosts in summary page.
we are creating the report as described (python3 -m openvasreporting -i <report.xml> -o <report.xlsx>)
Is this an expected behaviour?

Regards Thomas
![hosts](https://user-images.githubusercontent.com/42620376/60077232-d4bb2a80-9729-11e9-9d06-4c054aa6f8ab.png)

**Comment by TheGroundZero** [comment]
I'll have to look into this. I recall there's some weird quirck with the report's output and/or perhaps my phrasing is wrong.

Since this issue is related to the openvasreporting tool and not openvasreporting_server, could you reopen your issue [there](https://github.com/TheGroundZero/openvasreporting/issues)? I've enabled issues in that project as well.  
This is just to be able to properly follow up on issues and ideas for the 2 tools.
